// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbhhkvlkzilltromcjzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiaGhrdmxremlsbHRyb21janp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjE0ODksImV4cCI6MjA2MDczNzQ4OX0.EFJULFJyw7LSd-m0XIN9LTiU5TZQPvA2KCTh1PWVvi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);